repos:
  - repo: https://github.com/batmac/pre-commit-zig
    rev: v0.3.0
    hooks:
      - id: zig-fmt

      - id: zig-build
        stages: [pre-push] # Only run on git push

      - id: zig-build-test
        stages: [pre-push] # Only run on git push
